version: '3'
services:
    laravel_server:
        build:
            context: .  #current folder
            dockerfile: ./docker/Dockerfile
        container_name: larvel_framework
        working_dir: /var/www/html
        ports:
            - 9001:80
        volumes:
            - .:/var/www/html #move all of this folder to this address
            - ./docker/nginx_log:/var/log/nginx #move folder nginx_log to sv
            - .docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
            - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
        links:
            - mysql
    mysql:
        image: mysql:5.6
        container_name: larvel_mysql
        ports:
            - 9002:3306 #3306 is port of mysql
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
